const TAG = {
  LOADING: {
    VISIBLE: "WAITING_RESPONSE",
    INVISIBLE: "GET_RESPONSE",
  },
  AUTH: {
    SIGN_IN: "ADMIN_SIGNIN",
    SIGN_OUT: "ADMIN_SIGNOUT",
  },
  TOAST: {
    INFO: "DISPLAY_NOTICE",
    INVISIBLE: "HIDDEN",
  },
};
export default TAG;
